title: "OnlineProver"

pagetitle: "OnlineProver"

lang_name: English

author:
  bio: >-
    **Modern Approaches and Tools for Teaching Classes at the University Level in Theoretical Computer Science Courses of Logic, Types, and Semantics** 
    <br> 
    Initiative no: **FBR-PDI-025** <br>
    <br>    
    <img src="/_pages/images/EEA-and-Norway_grants.png"/>
    <br>
    <br>
    Working together for a green, competitive and inclusive Europe
  links:
    - label: "EEA and Norway Grants"
      url: "https://www.eeagrants.sk/en/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/onlineprover/"
    - label: "TUKE"
      url: "https://www.tuke.sk/"
    - label: "UiO"
      url: "https://www.uio.no/english/index.html"


footer:
  links:
    - label: "EEA and Norway Grants"
      url: "https://www.eeagrants.sk/en/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/onlineprover/"
    - label: "TUKE"
      url: "https://www.tuke.sk/"
    - label: "UiO"
      url: "https://www.uio.no/english/index.html"
